### ISSUE TITLE
Inconsistencies with function implementation

### ISSUE THREAD

**Issue by jability** [tuhdo/semantic-refactor#1]
Hi,

I've noticed some errors when implementing functions:
For instance with this class:
```c++
class Fixed
{
	public:
		Fixed(void);
		Fixed(Fixed const & src);
		~Fixed(void);
		Fixed &	operator=(Fixed const & rhs);

	private:
		int			_fpv;
		int const	_nfb;
};
```
Generating getters and setter do not work.

In addition, generating class implementation gives:
```c++
Fixed::Fixed(void ) {
	
}

Fixed Fixed(const ::Fixed& src) {
	
}

Fixed::~Fixed(void ) {
	
}

Fixed Fixed::=(const Fixed& rhs) {
	Fixed b;

	return b;
}
```
As you can see, the *copy constructor* and the *operator overloading* are all screwed up.
Thank you for taking a look !

By the way, just wanted to say impressive work so far, can't tell you how excited I am for this tool !

**Comment by tuhdo** [comment]
Thank you for your wonderful report that helps improving this package. I've fixed it. Could you check it again?

**Comment by tuhdo** [comment]
@jability I also implemented constant member initialization for constructors when a class contains any. However, the value is empty for user to fill in because usually user fills other values anyway.

**Comment by tuhdo** [comment]
@jability Now it should handle all operators and functions properly, even friend functions. You can use this example to test:

```c++
#include <iostream>

class Fixed
{
public:
    Fixed(void);
    Fixed(Fixed const & src);
    ~Fixed(void);
    Fixed & operator =(Fixed const & rhs);
    Fixed & operator +(Fixed const & rhs);
    Fixed & operator %(Fixed const & rhs);
    Fixed & operator +=(Fixed const & rhs);
    Fixed & operator ^(Fixed const & rhs);
    Fixed & operator ~();
    Fixed & operator ++();
    Fixed & operator *(Fixed const & rhs);
    Fixed & operator/(Fixed const & rhs);
    Fixed & operator/=(Fixed const & rhs);
    Fixed & operator[](Fixed const & rhs);
    bool operator==(const Fixed& rhs);
    bool operator!=(const Fixed& rhs);
    friend std::ostream& operator<<(std::ostream& stream, Fixed const & rhs);
    friend std::ostream& operator>>(std::ostream& stream, Fixed const & rhs);
    Fixed & operator->();
private:
    int         _fpv;
    int const   _nfb;
};
```

**Comment by jability** [comment]
@tuhdo Yes ! It works perfectly.
I think I found a few issues but I'm not on my usual computer so I'll report back later. Thanks
