### ISSUE TITLE
c++ pointer types appear not to be moved.

### ISSUE THREAD

**Issue by mijoharas** [tuhdo/semantic-refactor#11]
example is easiest to demonstrate:
`example.h`
```c++
namespace name1
{
namespace name2
{
class Class
{
public:
    something::Tag* getTagPointer();
}
}
}
```
if we try and generate function implementation in this file:

`example.cpp`
```c++
namespace name1
{
namespace name2
{
// we generate function implementation to here.
}
}
```

We get:
```c++
something::Tag name1::name2::Class::getTagPointer()
{
}
```

which has the problem that it should be `Tag*`. Another thing that is not a problem, but I thought didn't need to happen was the `name1::name2` as we are already inside the scope of those namespaces within our `.cpp` file.

**Comment by mijoharas** [comment]
I just tested and it looks like you do handle references, just with a space, so

```
something::Tag& getTagReference();
```

becomes:
```
something::Tag & name1::name2::Class::getTagReference()
{
something::Tag b;

return b;
}
```

**Comment by tuhdo** [comment]
Thanks for the report. I will get into it soon.

**Comment by tuhdo** [comment]
@mijoharas It is fixed. Once again thanks for you report.

**Comment by mijoharas** [comment]
Thanks @tuhdo :+1:
