### ISSUE TITLE
srefactor-refactor-at-point Error when creating menu.

### ISSUE THREAD

**Issue by hhirsch** [tuhdo/semantic-refactor#13]
When I call srefactor-refactor-at-point I only get: Error when creating menu.

**Comment by tuhdo** [comment]
Thanks for the report. Could you tell me how to reproduce the bug? And what's your Emacs version?

**Comment by hhirsch** [comment]
My srefactor is the one that came with emacs 20150717.1039 and my emacs version is 24.4.50.2 (i686-pc-linux-gnu, GTK+ Version 3.4.2) of 2014-08-29

**Comment by tuhdo** [comment]
Do ypu a code sample and where should i move point on that sample?

**Comment by hhirsch** [comment]
This file: https://github.com/GlPortal/glPortal/blob/master/source/Portal.cpp

Any line, any position.

**Comment by tuhdo** [comment]
I fixed this problem. The issue is there's a check whether `evil-mode` is active but without checking `evil-mode` exists at first.

Thanks again.

**Comment by hhirsch** [comment]
Cool. Will the updated version in melpa any time soon?

**Comment by tuhdo** [comment]
Yes. You just need to wait for it to update the list. It should be about an hour.

**Comment by hhirsch** [comment]
Thank you for fixing. I can confirm that everything works fine now.

**Comment by appetrosyan** [comment]
Need to reopen. Fresh install on Mac OS X. Installed it via use-package. Same error message.

**Comment by hhirsch** [comment]
@appetrosyan Sounds like your srefactor version is outdated, you can get the newest one from melpa.

**Comment by appetrosyan** [comment]
Did just that, latest version on melpa is 20180703.1810, which looks to be outdated. I'll try installing from GitHub and see if that fixes the issue.

**Comment by hhirsch** [comment]
A Version from 2018 should have the fix. I am confused. @tuhdo Any idea?

**Comment by appetrosyan** [comment]
I installed the latest version, the fix doesn't work. My opinion is that something else prevents the menu from loading, and it might be completely unrelated to the previous issue, except the error message is the same.
