### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by avatar29A** [tuhdo/semantic-refactor#14]
Hi. I tried to install plugin on Emacs 24.5 under Windows 10 and I got error

srefactor.el:102:1:Error: Cannot open load file: no such file or directory, srefactor-ui

Can you help me? Thanks.

**Comment by avatar29A** [comment]
I downloaded srefator-ue.el from repository and put into emacs.d near srefactor.el. It's help me.

I don't know why this file not download from elpa repository.

**Comment by tuhdo** [comment]
It's strange. Was you installing from [MELPA](https://melpa.org/)? It should work if the package is installed from there. Maybe just a bad installation; you should try again.

**Comment by avatar29A** [comment]
I  looked now. Actually i installed package from n/a repository. I should was click to other version and setup it.

![image](https://cloud.githubusercontent.com/assets/1295709/11492067/f5f1b23c-9809-11e5-9b2b-681404452d67.png)
