### ISSUE TITLE
Lisp: Cons literals losing space before the dot

### ISSUE THREAD

**Issue by cconnett** [tuhdo/semantic-refactor#15]
Cons literals that get reformatted on a new line are losing the space before the dot. This is causing them to no longer be cons literals and instead become lists with an unexpected in the second symbol.

    (append '(("a" .c++-mode)
              (b .2))
            a)

**Comment by tuhdo** [comment]
Thanks for the report. I will look into it soon.

**Comment by tuhdo** [comment]
The bug was fixed. Please report if you find more. Thanks again.

**Comment by cconnett** [comment]
Thanks for the speedy fix!
