### ISSUE TITLE
error with emacs pre 24.4

### ISSUE THREAD

**Issue by zbelial** [tuhdo/semantic-refactor#2]
subr-x is a new built-in library in emacs 24.4, so srefactor can't be used in emacs pre 24.4. 
A declaration about this in Readme is much better.

**Comment by tuhdo** [comment]
Thanks about that. I will fix it soon.

**Comment by tuhdo** [comment]
@zbelial I fixed it. Thanks for your report. It will future users.

**Comment by tuhdo** [comment]
Actually there's more problem with Emacs 24.3 than that, since CEDET is less functional than current Emacs 24.4. So I added a note that explicitly states Semantic Refactor only supports Emacs 24.4 or above at the moment.
