### ISSUE TITLE
Generated functions start immediately after close brackets

### ISSUE THREAD

**Issue by Spauldo** [tuhdo/semantic-refactor#20]
When i generate function implementation in the other file, each function begins immediately after the close bracket of the previous function.  For example:

```
Map::Map() {
	
}string& Map::get_room_name() {
	string b;

	return b;
}
```

I'm on Emacs 24.5 on Kubuntu 15.10.  I installed semantic-refactor tonight, and installed CEDET about a month ago, both via el-get.  I have various other packages as well, including company.

As an aside, is there any way to get it to follow K&R style?  I've set c-default-style to "stroustroup", although from what I understand that's just for indenting.  An example of what I want is below:

```
Map::Map()
{
    
}

string&
Map::get_room_name()
{
    string b;

    return b;
}
```

It's not a huge deal on either count, but it'd be nice.

**Comment by tuhdo** [comment]
Thanks for the report, I will fix it. As for the style formatting, I don't plan to do it as there are existing formatting tools already, and one of them `clang-format` is already integrated with Emacs.

**Comment by tuhdo** [comment]
I fixed it. Thanks again.

**Comment by Spauldo** [comment]
Sorry it took so long to test.

I've verified it works now.  Thanks, man!
