### ISSUE TITLE
Key bindings for menu are invalid

### ISSUE THREAD

**Issue by mssun** [tuhdo/semantic-refactor#21]
I can't use number key bindings to select options inside menu. This issue can be reproduced by following instructions:

1. `srefactor-refactor-at-point` to open *Srefactor Menu* buffer, it shows several actions which you execute by press 1-9 keys or click on it.
2. press any number keys will only execute the first action

I did read sources of semantic-refactor and found this code to define key bindings:
https://github.com/tuhdo/semantic-refactor/blob/master/srefactor-ui.el#L324
```
(defvar srefactor-ui--shortcuts-keymap
  (let ((km (make-sparse-keymap)))
    (dolist (k '(9 8 7 6 5 4 3 2 1))
      (let ((cmd (srefactor-ui--digit-shortcut-command-name k)))
        ;; Define a shortcut command.
        (defalias cmd
          `(lambda ()
             (interactive)
	       (srefactor-ui--refactor-action (get-char-property (point) 'button))))
        ;; Bind it to a digit key.
        (define-key km (vector (+ k ?0)) cmd)))
    km)
  "Digit shortcuts keymap.")

```

It seems that for each number key (`k`), you will bind to a function (`srefactor-ui--refactor-based-on-tag-class-k`). This function will get the item which the point at and execute the action. That's why pressing every key will only execute the first action, because of the position of the `point`.

I tried to fix this issue, but I'm not familiar with elisp. Do you have any ides?

**Comment by tuhdo** [comment]
Thanks for the report. I will fix it soon.

**Comment by tuhdo** [comment]
I fixed it. Thanks again.
