### ISSUE TITLE
Generate Getters and Setter works fine, Generate Function Implementation goes wrong/

### ISSUE THREAD

**Issue by nxty2011** [tuhdo/semantic-refactor#25]
Hello, thank u for your nice work. I encounter a problem when I tried to get through your demos at "Generate Function Implementation" step.

I opened a class header file buffer, declared the prototype, and type the command "SPS m r" in the class body. In the popup mini-buffer, I selected the number 3, which is generating function implementation function. After typing "3", no implementation code was input in the corresponding class source file as the demo shown. Instead, a "dired" buffer of current dir is open in another window.

I've disabled all other layers but semantic layer to redo the steps, but it went to the same result. After searching the internet, few related link has been found. 

My spacemacs version is 0.105.22, at the develop branch and kept update up to date. Any suggestions are appreciated.

**Comment by tuhdo** [comment]
Hello,

Could you give me more details?

1. Are you in a Projectile-aware project, e.g. Git?
2. Is the corresponding source file in the same directory?
3. Could you give me a minimum sample code to reproduce?

Thanks.

**Comment by nxty2011** [comment]
OK, thank u for your quickly reply.

1. I used .projectile instead.
2. The source file and header file are in the same directory.
3. Sample code in the header file(number_string.h).
```c++
#include <iostream>
#include <string>

class NumberString
{
private:
  int num_;
  string str_;
public:
  NumberString();

  void SetNumber(const int& num);
  void PrintString() const;
};
```
Sample source file(number_string.cc)
```
#include "number_string.h"
```

More details could be provided if you need.

**Comment by tuhdo** [comment]
I still cannot reproduce. I used `.c` file. Maybe you should change into `.cpp`, as the other file selection is based on Projectile's. In this case, Projectile has no other file switch for `.cc` file. Regardless, it should put you into a `.c` file if no valid other file was found, not a Dired buffer.

Could you turn on `M-x toggle-debug-on-error`?

Note that if you generate a function in `c-mode`, it won't insert namespace for you i.e. you only get `void SetNumber(const int& num)`, not `void NumberString::SetNumber(const int& num)`.

**Comment by nxty2011** [comment]
Ah, yes! It is the suffix that causes the problem. I change the source file name into a name ending with `.cpp`, then **semantic** works!
 
I guess **Generate Function Implementation** could only recognize a source file end with `.cpp` rather than `.cc,` then it would try to open a `.cpp` source file in the directory, which does not exit. It open a **dired** buffer instead.

Thank your for your analysis and advise. 

Somehow, a c++ source file ending with `.cpp` is common(google coding style), I would try to find a way to add `.cc` as a file switch of **projectile**.
