### ISSUE TITLE
Add function prototype creation to unknown functions

### ISSUE THREAD

**Issue by tomkulaga** [tuhdo/semantic-refactor#27]
for example:

void BarClass::fooFunc()
{
    int result = bazFunc();
}

with the mouse above bazFunc() it would allow me to create either a free function or a member fuction in BarCalss

**Comment by tuhdo** [comment]
Thanks for the suggestion. It's doable. I will add the feature soon.

**Comment by tomkulaga** [comment]
Thanks. No problem :)

**Comment by tuhdo** [comment]
Well, actually it is done already. You should see the choice `Generate Function Prototype (Other file)` and it will allow you to switch to the file with `BarClass`, then select where to place it. If you want to generate a free function, put it outside `BarClass`, otherwise inside.
