### ISSUE TITLE
srefactor--extract-region complains about wrong number of arguments

### ISSUE THREAD

**Issue by rhymer** [tuhdo/semantic-refactor#29]
To reproduce:
1. Select a region of C++ code.
2. `M-x srefactor--extract-region`
In the echo region it says:

> Wrong number of arguments: (lambda (extract-type)

OS: OpenSUSE 11
Emacs: 24.5.1
Using spacemacs 0.105.22 with c-c++ layer.

Did I miss something? Thanks.

**Comment by tuhdo** [comment]
Do you have a sample code? Did you get the error on an unsaved buffer or a file? Thanks.

**Comment by rhymer** [comment]
I tried both saved file and unsaved buffer. The example I used is [Simple C++ examples](http://www.inference.phy.cam.ac.uk/teaching/comput/C++/examples/RandDemo6.shtml).
1. select the for loop under `// Perform N experiments.`
2. `M-x srefactor--extract-region` produces the same error.
I also tried to use `emacs -Q` and loaded `srefactor` afterwards. Same error message.

**Comment by tuhdo** [comment]
@rhymer I fixed it. You shouldn't use `srefactor--extract-region`, as it is supposed to be used internally by other functions in `srefactor`. I removed the interactive use of it. The only command you should be using is `srefactor-refactor-at-point`, and upon analyzing, it gives you a list of possible choices. I believe Spacemacs has a key binding for it, which should be `SPC r`.

**Comment by tuhdo** [comment]
Here is the demo:

![test_srefactor](https://cloud.githubusercontent.com/assets/4818719/19211935/24caf5c4-8d72-11e6-89df-79384aae7cc3.gif)

**Comment by tuhdo** [comment]
Nevertheless, I found a bug in Semantic. That is, in your example code contains a macro with a partial comment:

```c++
#define ranf()                                                          \
    ((double)random()/(1.0+(double)RAND_MAX)) // Uniform from interval [0,1) /*
```

You should delete the `/*` at the end, otherwise Semantic is confused and thinks that is an opening comment for the `main` function, thus got analyzing all wrong.

**Comment by rhymer** [comment]
@tuhdo It works like a charm! Didn't realized that I was using the wrong function. BTW I am a big fan of your tutorials! Thanks for sharing!
