### ISSUE TITLE
srefactor-refactor-at-point failing with error message

### ISSUE THREAD

**Issue by morbidrsa** [tuhdo/semantic-refactor#3]
srefactor-refactor-at-point is failing with an error message. When I want to extract a region to a function, I get the following error message:

> You can run the command `srefactor-refactor-at-point' with M-RET
> call-interactively: Wrong number of arguments: (lambda nil (interactive "P") (kill-buffer (current-buffer)) (delete-window (car (window-list))) (select-window srefactor-ui--current-active-window) (srefactor--refactor-based-on-tag-class (car (nth (- 1 1) (items srefactor-ui--current-active-menu))))), 1

I'm using Emacs 24.4.1 from openSUSE Tumbleweed and semantic-refactor from MELPA.

I'd be thankful for any advice,
Johannes

**Comment by tuhdo** [comment]
Thank you for your report. I know where it fails. It is the result of some refactoring I did a while ago. I will fix it asap. I really need to write a test suite for regression testing.

**Comment by tuhdo** [comment]
@morbidrsa I fixed it. Please check it again. Thanks.

**Comment by morbidrsa** [comment]
Works with current HEAD, thanks for resolving :-)
