### ISSUE TITLE
Missing const qualifier when generating const function implementation

### ISSUE THREAD

**Issue by NikolayBobovnikov** [tuhdo/semantic-refactor#30]
When declaring const member function, like this:

class A {
...
void foo() const;
};

and doing "Generate function implementation (other file)", function generates without const qualifier, like so:

void A::foo() {
}

Expected result:

void A::foo() const {
}

**Comment by tuhdo** [comment]
Sorry for the long delay. I've just fixed it.

Thank you for the report.

**Comment by NikolayBobovnikov** [comment]
Great! Thanks :+1:
