### ISSUE TITLE
No insert class name inside namespaces

### ISSUE THREAD

**Issue by Curiosidad-Racional** [tuhdo/semantic-refactor#31]
--- foo.hpp
``` cpp
namespace one {
namespace two {
class Test {
    Tes|t(); // cursor at |
};  }}
```
--- foo.cpp
``` cpp
namespace one {
namespace two {

}}
```

M-x srefactor-refactor-at-point

--- foo.cpp
``` cpp
namespace one {
namespace two {
Test() {
    
}
}}
```

missing Test:: preceding Test()

Thanks

**Comment by tuhdo** [comment]
I push a fix. Please try it again.

Thanks for the report.

**Comment by Curiosidad-Racional** [comment]
Thank you for your prompt reply. The fix works but:

--- foo.hpp
``` c++
namespace one {
namespace two {
class Test {
    Tes|t(); // cursor at |
}; }}
```

M-x srefactor-refactor-at-point and select insert Inside namespace one.

--- foo.cpp
``` c++
namespace one {
Test::Test() {
}
namespace two {
}}
```

mising two:: preceding Test::Test()

I hope this can help you:

``` lisp
(let* ((parents-pos (srefactor--tag-parents-string tag))
       (parents-remove (concat parents-pos (car tag) "::"))
       (parents (srefactor--tag-parents-string func-tag)))
  (insert (replace-regexp-in-string (concat "^" parents-remove) "" parents)))
```

**Comment by tuhdo** [comment]
I am ignoring namespace parent at the moment, as currently srefactor tries to retrieve all upper parents of a tag. As a result, when generating a function definition, srefactor inserts all namespaces as part of the prefix of a tag, even though the tag is already inside such namespaces. I will fix this later.

**Comment by tuhdo** [comment]
I fixed the issue. Please have a look again.

**Comment by Curiosidad-Racional** [comment]
It works fine. Thanks very much.
