### ISSUE TITLE
No indentation when called from emacs --script

### ISSUE THREAD

**Issue by kureta** [tuhdo/semantic-refactor#33]
Exact same code behaves differently when run in interactive mode vs. as a script. Inside Emacs it works as intended but when run as a script it inserts newlines as expected but does not indent lines at all. All lines start at the first column.

This is the file I run from inside Emacs using `eval-buffer`

```
(dolist (file (directory-files "~/Documents/OpenMusic Workspace/fractal-generator/elements" t "\\.omp$"))
  (find-file file)
  (goto-char (point-min))
  (when (search-forward "(load-lib-for" nil t)
    (replace-match "\n(load-lib-for"))
  (when (search-forward "(setf" nil t)
    (replace-match "\n(setf"))
  (srefactor-lisp-format-sexp)
  (save-buffer)
  (kill-buffer))
```

And this is the emacs script file

```
#!/usr/local/bin/emacs --script

(package-initialize)
(require 'srefactor)
(require 'srefactor-lisp)

(dolist (file (directory-files "~/Documents/OpenMusic Workspace/fractal-generator/elements" t "\\.omp$"))
  (find-file file)
  (goto-char (point-min))
  (when (search-forward "(load-lib-for" nil t)
    (replace-match "\n(load-lib-for"))
  (when (search-forward "(setf" nil t)
    (replace-match "\n(setf"))
  (srefactor-lisp-format-sexp)
  (save-buffer)
  (kill-buffer))
```

**Comment by kureta** [comment]
Also commandline version is impossibly faster compared to the interactive version. That might be a clue. Maybe I have to require a few other packages.

**Comment by tuhdo** [comment]
Thanks for the report. I'll look into it.

**Comment by tuhdo** [comment]
The problem is that your files were opened not in `emacs-lisp-mode`  but in `fundamental-mode`. Set Emacs Lisp mode: `(emacs-lisp-mode)` before `find-file file)` and it should work properly.
