### ISSUE TITLE
No rename option for class members?

### ISSUE THREAD

**Issue by danyloM** [tuhdo/semantic-refactor#36]
When I place the cursor over a member function or variable of a C++ class (or even the class name, namespace name, etc.) and press `M-RET`, I get the following popup:
```
Functions: void foo (double & bar)

  [1] Move (Current file)
  [2] Generate Function Pointer (Current file)
  [3] Generate Function Implementation (Other file)

[Cancel]
```
There is no option to rename the member function/variable/class name/namespace name. I only get the option `Rename local variable (Current file)` for variables defined locally within function definitions. My questions are:

* How do I rename anything locally (i.e. a namespace, a class, class members, etc.)?
* How do I rename anything globally (i.e. in all files of the current Projectile project, for example)?

Thanks again for your help.

**Comment by tuhdo** [comment]
Currently, only local variable rename is available. To rename anything outside of that e.g. a function name, it is required to update the whole project. However, the Semantic parser is written in Emacs Lisp, and Emacs Lisp blocks when Semantic parses large project (that is, you must wait for Semantic to finish). 

For globally rename _correctly_, types must be taken into account. Grep style renaming does more harm than good in a C++ project.  You may want to look at rtags: https://github.com/Andersbakken/rtags, if you want globally renaming, though it's more involved to setup.

**Comment by danyloM** [comment]
I see, that's too bad. I would have guessed variable renaming is one of the most widely used refactoring methods? Perhaps something like irony-refactor could be made in the future to have it non-blocking. Rtags does indeed seem to have quite an invasive installation.

**Comment by tuhdo** [comment]
I intend to write a tag parser based on GCC that can retrieve tag information for Emacs to use, so we won't need Semantic to parse; Semantic only needs to use that tag database. Only when we have a parser that uses the infrastructure of a compiler (e.g. similar to how people are creating tools with Clang), we can perform globally refactoring. But maybe I will start working on it next year. Now is not the time.

**Comment by danyloM** [comment]
Ok, good to hear that there are at least plans.

**Comment by hlambda** [comment]
@tuhdo What's the status of the implementation?

(I'm currently learning elisp and would be interesting in working on a small project. I might be interested in collaborating in this feature.)
