### ISSUE TITLE
no class name when generating member function implementation

### ISSUE THREAD

**Issue by hyOzd** [tuhdo/semantic-refactor#37]
When I try to create function implementation from a C++ member function, class name is ignored if I select a target position. Here is how it happens:

* I move cursor over my member function declaration, trigger srefactor, select option "Generate Function Implementation"
* srefactor switches to my .cpp file, lists other members 
  * if I don't make any selection (first include is automatically selected), and press enter, function is generated as expected
  * if I make another selection other than first option in the list, it creates the function without the class name (like a global function)

I've uploaded my files to [this gist](https://gist.github.com/hyOzd/d8cb65297a66f8da7fafff1c8e4157a4).

**Comment by sukeyisme** [comment]
me too

**Comment by sukeyisme** [comment]
[https://github.com/tuhdo/semantic-refactor/blob/master/srefactor.el#L847](url) i remove this line ,everything right. but i don't know why.

**Comment by sukeyisme** [comment]
https://github.com/tuhdo/semantic-refactor/blob/master/srefactor.el#L847

**Comment by tuhdo** [comment]
I pushed a fix that replaced a better check for parent string insertion. Previously, the check was made for fixing issue #31.

During your report, I was busy releasing my new book: [Oprating System: From 0 to 1](https://tuhdo.github.io/os01/), so I could not get to fix this bug. Sorry for the delay.
