### ISSUE TITLE
Generated function implementations misrepresent "const char*" function parameters.

### ISSUE THREAD

**Issue by UndeadKernel** [tuhdo/semantic-refactor#38]
Say I have the class CMyClass, in a heder file that defines the following function:
    `void myFunction(const char* first_string, const char* second_string);`

If I ask to "Generate Function Implementation", the following function will be generated:
    `void CMyClass::myFunction(char first_string, char second_string) { }`

Notice that the string parameters were not passed as expected.

**Comment by tuhdo** [comment]
Thanks for the report. I will fix it soon.
