### ISSUE TITLE
No available action

### ISSUE THREAD

**Issue by MatthewBregg** [tuhdo/semantic-refactor#4]
After performing a rename once/twice, I pretty consistently get No available action. when I try to srefactor-refactor-at-point.
This happens across various files C++ files.

**Comment by tuhdo** [comment]
Do you have any functions that have the same name as your local variables?

**Comment by tuhdo** [comment]
It's not related, nvm.

**Comment by tuhdo** [comment]
@MatthewBregg Thanks for your report. I fixed it.
