### ISSUE TITLE
Refactoring rename does not seem to rename function parameters. 

### ISSUE THREAD

**Issue by MatthewBregg** [tuhdo/semantic-refactor#5]
Example:
(C++)
int factorial(int n){
    if(n == 1){return 1;}
    return n*factorial(n-1);
}
Attempting to rename n to say foo leaves the int n argument unchanged.

Also, would it be possible to get the ability to rename functions?

Thanks for this great tool, it's looking great so far!

**Comment by tuhdo** [comment]
Hi,

Thanks for the report. I will look into it. 

> Also, would it be possible to get the ability to rename functions?

If it's just local rename, then it's possible. For global rename, also doable but it would block Emacs because if you have large source tree then it would take too long and block Emacs. Actually, rename references are available with `semantic-symref` by running the command on a symbol, wait it gather and display the references, then press <kbd>R</kbd> to rename references. But it would take long for large projects to correctly analyze and retrieve references.



> Thanks for this great tool, it's looking great so far!

Glad you like it!

**Comment by MatthewBregg** [comment]
Thanks for the response. 

I would certainly appreciate the ability to rename functions globally, even if it could lock up emacs during the process for large code bases, but I can diffidently see some people getting frustrated if they weren't expecting it. Perhaps display a message in the minibuffer when it runs that this may lock up emacs?

Keep up the good work.

**Comment by tuhdo** [comment]
Actually, you can already do that with stock Semantic for mass references. What you need to setup:

- Enable `semanticdb-minor-mode` and GNU Global integration for Semantic:

```elisp
(setq-default semantic-symref-tool 'global)
(when (cedet-gnu-global-version-check t)
  (semanticdb-enable-gnu-global-databases 'c-mode t)
  (semanticdb-enable-gnu-global-databases 'c++-mode t))
```

- Install GNU Global.
- From your project root, run `gtags` to create a tag database.
- Then, run `semantic-symref` (bound to <kbd>C-c , G</kbd>.
- If you project is not too large, or the gathering symbol is not used in too many places (i.e. in hundreds of files), then references should appear insant or in a brief moment. 
- You can navigate in reference buffer with <kbd>n</kbd> and <kbd>p</kbd>, open fold with <kbd>SPC</kbd>, expand all with <kbd>C-c C-e</kbd> and collapse all with <kbd>C-c C-r</kbd>.
- Now, you can rename symbol with <kbd>R</kbd>: you must move the cursor on the inner-most node for references to take effect. Note that it only renames all the symbols in a file, not all references in the `*Symref*` buffer.

**Comment by MatthewBregg** [comment]
Thank you for the excellent guide. 
I played around with it a bit and it seems like a fairly nice way to rename functions in a project.  
Thanks!

**Comment by tuhdo** [comment]
I fixed it. Please try again.

**Comment by MatthewBregg** [comment]
Thanks, it works now!
