### ISSUE TITLE
[enhancement] How to customize the getters and setters rules?

### ISSUE THREAD

**Issue by andyque** [tuhdo/semantic-refactor#7]
In my class, I have defined the following members:

```cpp
class Foo
{
public:
private:
        int _age;
        std::string _name;
};
```

Now in srefactor, it will always generate the following getters and setters:

```cpp
class Foo
{
public:
         int get_age() const {
        return _age;
    }
    void set_age(const int _age) {
        this->_age = _age;
    }

    const std::string get_name() const {
        return _name;
    }

    void set_name(const std::string _name) {
        this->_name = _name;
    }

private:
        int _age;
        std::string _name;
};
```

It's really nice, but I do want to do some customizations.

1. I want to change action to "other file" like "generate function implementation". I don't want to just inline these functions.

2. I want to customize the function signature.
Now we could customize 

```
(setq srefactor--getter-prefix "get")
(setq srefactor--setter-prefix "set")
```

But we can do more..  If only I could  generate some CamelCase getters and setters that would be great.
Thanks.

**Comment by tuhdo** [comment]
> I want to change action to "other file" like "generate function implementation". I don't want to just inline these functions.

Sure it could be added.

> But we can do more.. If only I could generate some CamelCase getters and setters that would be great.

Do you mean something like "GetAge()" or "SetAge()" even when the member variable is `_age`? Surely it can be done but a user must be aware that any underscore will be stripped in variable names when a getter/setter is generated.

**Comment by andyque** [comment]
>Do you mean something like "GetAge()" or "SetAge()" even when the member variable is _age? Surely it can be done but a user must be aware that any underscore will be stripped in variable names when a getter/setter is generated.

What I want is something like "prefix" + "regular expressions" + "variable name".

- The prefix is the original "srefactor--getter-prefix".
- The "regular expressions" is something like "[_|m_]".

For example:

If I define a variable like this:

```
int _age;
int m_nAge;
```

We could provide a regular expressions like "_" or "m_n", the regular expression  will matches the prefix of a member variable and the matching part could be removed.(yes , we could let users customize this behavior)

We could also provide a option to translate the remaining part "age and Age" to choose whether upper case the first character or not.

Instead of provide only one option for getter-prefix, we could provide four:

1. srefactor--getter-prefix. (a string)
2. srefactor--getter-removal-regex (default nil)
3. srefactor--getter-uppercase-first-character-p (t or nil, default nil)

So if I define the following member variable:

```
int _age;
```

And add the customization to my .emacs:

```
(setq srefactor--getter-prefix "get")
(setq srefactor--getter-removal-regex "_")
(setq srefactor--getter-uppercase-first-character-p t)
```

So the finally getters and setter would become:

```
int getAge()const;
void setAge(int age)
```

**Comment by tuhdo** [comment]
Ok sounds good to me. Will implement, thanks.

**Comment by tuhdo** [comment]
@andyque I implemented the features you request. Please give it a try.
