### ISSUE TITLE
Fix issue with function signature generation

### ISSUE THREAD

**Issue by tuhdo** [tuhdo/semantic-refactor#9]
After some refactoring function like this can't be generated anymore:

```c++
void MyClass::myFunc(std::vector<std::string> argument)
{}
```

`std::string` is omitted, which was working in previous release.

**Comment by tuhdo** [comment]
@mijoharas this issue is fixed. Thank you very much for reporting.

**Comment by mijoharas** [comment]
brilliant, :+1: @tuhdo. Thanks!

**Comment by mijoharas** [comment]
just tried it out, works great!
